### ISSUE TITLE
Replace 'antd' with 'antd-mobile'

### ISSUE THREAD

**Issue by nagayamaryu** [taiki0000/titech-wallet#7]
スマホで見てもらうことを前提とするならばモバイル用のantd-mobileにするべきではないか
https://mobile.ant.design/
現在のものをiPhoneで見てみたところ、tokenのリストのテーブルが画面からはみ出ていて横スクロールしないと見れない

**Comment by taiki0000** [comment]
アンドロイドで検証する。

**Comment by taiki0000** [comment]
アンドロイドでデザイン崩れてないかみて欲しい、ついでに俺にDMでアンドロイドの表示のされ方をスクショで送って欲しい。
